version: '3.8'

services:
  web:
    build:
      context: .
    command: gunicorn webempresa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thos
      POSTGRES_DB: webEmpresa
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/app/static  # Añadir ruta para los archivos estáticos
      - ./media:/app/media    # Añadir ruta para los archivos de media
    depends_on:
      - web
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
