# Generated by Django 2.0.2 on 2019-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190811_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='', verbose_name='Contenido'),
        ),
    ]
