name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: thos
          POSTGRES_DB: webempresa
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libpng-dev postgresql-client
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Set up Database and Run Migrations
      env:
        DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/webempresa
      run: |
        python manage.py migrate
      working-directory: ./webempresa  # Cambia este directorio si es necesario

    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgrespassword@localhost:5432/webempresa
      run: |
        python manage.py test
      working-directory: ./webempresa  # Cambia este directorio si es necesario
