version: '3'

services:
  web:
    image: tu-usuario/tu-repositorio:latest
    build: .
    command: gunicorn tu_proyecto.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thos
      POSTGRES_DB: webEmpresa
